project:
  type: website

website:
  title: "Seeun Park"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "CV"
        file: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css    
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
        <meta name="robots" content="noindex, nofollow">

site-url: "https://spark-econ.github.io/"
resources:
  - robots.txt
